### ISSUE TITLE
Support a TOC for the book page

### ISSUE THREAD

**Issue by briandfoy** [davorg/perlschool#8]
A suggestion from [keath on /r/perl](https://www.reddit.com/r/perl/comments/ks78fp/new_perl_school_book_from_brian_d_foy_perl_new/gikf7mz/): put the table of contents on the Perl School page.

I can generate the TOC in any form that you like, and I auto generate it for Leanpub where I insert my own classes (see [Format Your LeanPub Table of Contents](https://briandfoy.github.io/format-your-leanpub-table-of-contents/)). 

I'm happy to send PRs for this, but sending PRs against a sqlite file is kinda weird. Maybe it's not a big deal.

**Comment by davorg** [comment]
Yeah. I like this idea. Let me think about it.

I guess you could send PRs against the `books.list` file (which is text version of the database).

**Comment by davorg** [comment]
I'm thinking I want three bits of text.

1. The current blurb (because that's what appears on the front page or the footer of the page). This is the only one that's mandatory
2. An optional extended description
3. A TOC

Then, if either of the second or third is defined, I'll insert a new section on the book page that displays them.

Currently, the `books.list` file has a single line per file. That's going to be harder for these extended attributes. I'm wondering if an external file is easiest - with a naming convention like `toc/<slug>.html` and `desc/<slug>.html`.

But I'm open to other suggestions.

**Comment by davorg** [comment]
Done in https://github.com/davorg/perlschool/commit/517d2f4c6197debe070afba43cf38445e3d11a35 and https://github.com/davorg/perlschool/commit/517d2f4c6197debe070afba43cf38445e3d11a35

**Comment by davorg** [comment]
Some information about how to use this fix.

I've added two new columns `toc` and `description` to the `book` table. They both expect to be given HTML.

I've also written some simple programs to make it easy to manipulate the contents of this column. You'll need the slug for your book - you can get that using `bin/get_slug`.

Then create one or two files in the new `data` directory. They should be called `<slug>.toc` and `<slug>.desc`. They should contain the HTML for the ToC and an extended description. They're both optional.

Then, if you run the program `bin/edit_extras <slug>`, it will take the contents of those files and put them in the correct place in the database.

Add the new data files to `git` and commit the changes to the database (`perlschool.db`). When you push those changes to GitHub, the build/deploy job will rebuild the web site and deploy it to GitHub Pages including your new information.

See these pages for examples of a ToC:

* https://perlschool.com/books/perl-taster/
* https://perlschool.com/books/the-best-of-perl-hacks/
